### ISSUE TITLE
你们用 CM6 没有这个烦恼吗？

### ISSUE THREAD

**Issue by zen010101** [cumany/Blue-topaz-examples#1]
你们在 checklist 状态下，输入汉字然后输入逗号，是否正常？

比如这一行：

- [ ] 你好，世界！

**Comment by cumany** [comment]
不知遇到了什么问题，输入测试一切正常。
这里给个小建议，输入checklist 可以先输入 “你好，世界！” 然后按两次ctrl+enter 即可

**Comment by conscloud** [comment]
![image](https://user-images.githubusercontent.com/18484709/155104802-28c0698a-c2c9-411f-aef7-d58bd9117263.png)
中文状态下输入标点符号，会处于选中符号的状态，光标不会自动向后，需要输入两次才行

**Comment by cumany** [comment]
最新的ob  0.13.30 应该修复了这个问题

**Comment by zen010101** [comment]
> 最新的ob 0.13.30 应该修复了这个问题

0.13.31 版本，经过测试，问题依旧。

**Comment by cumany** [comment]
留意官方更新吧 最近几个版本迭代都在修复 IME输入相关
