### ISSUE TITLE
插件影响Banner外观：Copy Button for code blocks插件

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [cumany/Blue-topaz-examples#13]
安装Copy Button for code blocks这个插件后Banner显示会有问题，不是紧迫的毛病，只是看起来对强迫症不友好。

**Comment by cumany** [comment]
ob目前不是已经自带代码块复制功能了，这个插件已经没多大用途了。
不过blue topaz主题还是修复了这个问题，更新到最新主题应该就解决了。
