### ISSUE TITLE
bsidian直接退出

### ISSUE THREAD

**Issue by chengpopeye** [cumany/Blue-topaz-examples#18]
Obsidian.0.14.6直接复制了Blue-topaz-examples中的.obsidian和88-Template文件,开启了外观和第三方插件配置,开启obsidian直接闪退

**Comment by cumany** [comment]
快速移植可以参考这个讲解 https://www.bilibili.com/video/BV18S4y1Y7Wb/

**Comment by chengpopeye** [comment]
好的
