### ISSUE TITLE
想请教一下关于cMenu的CSS样式调用问题

### ISSUE THREAD

**Issue by Myoontyee** [cumany/Blue-topaz-examples#20]
老哥你那个[cMenu增强仓](https://github.com/cumany/cMenu-Plugin/tree/1.1.30)没有issues，所以只能来这里提问了

> 插件已内置 remixicon 字体文件。图标代码可以参考 https://remixicon.com/
按照你readme里头的说辞，去[remixicon](https://remixicon.com/)找了一下，没找到下面这个`abc`对应的icon，看源码里是`any-key`，但是如下下图，没有这个logo……

**我的问题**：我现在想添加新的功能，想用这个类似的logo，并且是如下图这个`abc`一样可以制作一个直观显示的，有不同颜色背景的logo，我应该怎么做才能添加到cMenu插件里？
是通过`style.css`的样式调用吗？但是在你魔改的`\.obsidian\plugins\cmenu-plugin`目录下源码里没有找到调用的语句...请大佬教教我，谢谢！！

![图片](https://user-images.githubusercontent.com/40823733/165660871-e052e092-ab5b-419e-adc7-b2f0969be912.png)

```json
    {
      "id": "Enhanced-editing:text-background3",
      "name": "ZH增强编辑: 转换黄色背景",
      "hotkeys": [
        {
          "modifiers": [
            "Mod",
            "Alt"
          ],
          "key": "3"
        }
      ],
      "icon": "any-key"
    },
```

---

![图片](https://user-images.githubusercontent.com/40823733/165661145-55e8596f-eb66-44e3-a8ec-8ee53b4b2f7a.png)

**Comment by cumany** [comment]
styles.css 中 conten 里就是svg代码 更换 改颜色都可以
![image](https://user-images.githubusercontent.com/42957010/165662403-36e8897f-3946-44d7-8329-e4c99aa8d766.png)
