### ISSUE TITLE
get movie from douban BUG, if content is null.

### ISSUE THREAD

**Issue by xfap** [cumany/Blue-topaz-examples#21]
The Error appeared as below.
![image](https://user-images.githubusercontent.com/27057528/166138230-bb07fe3b-c6ff-42b7-868b-88d27c891a9e.png)

Take this movie(https://movie.douban.com/subject/35634039/) for example, where its content description is empty.

So the js code below ends with a error.
![image](https://user-images.githubusercontent.com/27057528/166138416-89398984-ffea-4e0c-98d0-eae21451f1a3.png)
```js
	summary = $("span[property='v:summary']").textContent??'-';
	genre = $("span[property='v:genre']").textContent??'-';
```
A simple change as below:
```js
	summary = $("span[property='v:summary']")?.textContent??'-';
	genre = $("span[property='v:genre']")?.textContent??'-';
```
Then the bug will be resolved.

**Comment by cumany** [comment]
Thanks! I'll fix it now!
