### ISSUE TITLE
BUG: 首页的笔记统计模块与emoji toolbar插件冲突

### ISSUE THREAD

**Issue by OriOYue** [cumany/Blue-topaz-examples#25]
当开启emoji toolbar插件，并重启obsidian后，首页的笔记统计模块会报错。

> ![1](https://user-images.githubusercontent.com/72482686/167581909-bd542059-b8be-4112-93f4-ef954849ae53.PNG)

**Comment by cumany** [comment]
两个解决办法1.把统计模块里的表情都删了 因为这个插件默认会把表情符号变成超链接
2. emoji toolbar插件设置关闭 增强表情符号的功能选项。

**Comment by cumany** [comment]
新版示例库（20220609）避免了表情的应用 已经不存在这个问题了
