### ISSUE TITLE
建议：是否可以将库中的文件夹都放到一个文件夹里，以减轻更新升级工作量。

### ISSUE THREAD

**Issue by OriOYue** [cumany/Blue-topaz-examples#26]
目前库中的有多个文件夹：00-Tips、10-Help、20Diary、30-Reading。。。99-Attachment文件夹等，
由于每个人的使用习惯不同，所以需要将这些文件夹迁移或者重命名，但这会导致升级更新库的工作量增大。

考虑到如果不动现在库中的文件夹，倒是最容易迁移的，但是库中默认的这8个文件夹会占用太多侧边栏空间，影响使用，所以是否可以将这些文件夹都放到一个文件夹里（如：Obsidian文件夹），让每个用户都不需要动库原来的这一个文件夹就可以轻松迁移。

当然大佬也可以征求QQ群里人的意见：是否需要将日记、模板、附件这三个文件夹单独列出来。

**Comment by cumany** [comment]
示例库的文件夹是可以改名的，建议用第三方工具（比如UltraReplace）批量查找替换，一般ob的参数都是在md，js，json这三种类型文件中。 这样功能几乎不受影响。
