### ISSUE TITLE
移植通过下拉框筛选文件，出现奇怪标识符，如何去除

### ISSUE THREAD

**Issue by weihaoxie** [cumany/Blue-topaz-examples#33]
![image](https://user-images.githubusercontent.com/6837658/173594642-a700656d-0b9d-462c-b758-0c7b26339ffe.png)

**Comment by cumany** [comment]
这个貌似dataview 更新到0.5.34版本出现的问题，目前解决办法回退dataview到之前版本，或者等下一班更新。
