### ISSUE TITLE
升级obsidian到0.15.2后，button文字位置发生错乱

### ISSUE THREAD

**Issue by weihaoxie** [cumany/Blue-topaz-examples#35]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/6837658/175507985-d500b557-4b3e-42f1-a29d-6fd6e1931fe8.png">

**Comment by cumany** [comment]
本人没有内测版等公版发布后更新

**Comment by zhongshangwu** [comment]
same with me

**Comment by cumany** [comment]
更新主题就正常了
