### ISSUE TITLE
20220630-lite中点击生成moc没有反应

### ISSUE THREAD

**Issue by lukeaust** [cumany/Blue-topaz-examples#42]
老版本中生成moc正常，但是新版本解压后打开，没有任何响应动作

**Comment by cumany** [comment]
这个因为文件夹路径变化造成路径失效 修复办法，打开button.md 文件
把88-Template 替换为 BT_Example/88-Template 即可解决

**Comment by lukeaust** [comment]
谢谢，已经找到原因了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cumany/Blue-topaz-examples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cumany/Blue-topaz-examples] 20220630-lite中点击生成moc没有反应 (Issue #42)





 
这个因为文件夹路径变化造成路径失效 修复办法，打开button.md 文件
 把88-Template 替换为 BT_Example/88-Template 即可解决
