### ISSUE TITLE
升级到0.15.6版本后，在文件列表中右键新建template后，新建文件的视图会在文件列表中

### ISSUE THREAD

**Issue by wasdty** [cumany/Blue-topaz-examples#43]
升级到0.15.6版本后，在文件列表中右键新建template后，新建文件的视图会在文件列表中，而不会在主视图中
![1658115079744](https://user-images.githubusercontent.com/18108625/179441418-2c4c40df-6d78-4d0c-aa75-ca771dc45187.png)
常规操作等按钮样式移位
![1658115158058](https://user-images.githubusercontent.com/18108625/179441486-bc0af1ab-1756-4cab-85d6-16ecd1bd1613.png)

**Comment by cumany** [comment]
1. ob 15.x 通病问题等ob优化
2.按钮移位 自己更新blue topaz 主题就可以了
