### ISSUE TITLE
请问如何方便使用本地图片作为电影库封面？

### ISSUE THREAD

**Issue by pikawindy** [cumany/Blue-topaz-examples#47]
能说一下使用影库本地图片的具体流程吗？
我是先生成豆瓣影片卡片，然后下载并改好图片名字放在attachment，再用metaedict修改。
如图
![Snipaste_2022-08-28_18-20-45](https://user-images.githubusercontent.com/63467634/187069236-ce49c3f1-cb14-4c5c-bdb8-e2f4a6c4ebae.jpg)
![Snipaste_2022-08-28_18-21-10](https://user-images.githubusercontent.com/63467634/187069244-4e81fd00-baaf-48bb-a0f4-8d9011916620.jpg)
问题是输入cover那和value是要我完整输入文件名字吗？例如：99-Attachment/你本应离开.jpg
这也太麻烦了点吧，还不如直接用外链。

**Comment by pikawindy** [comment]
感觉好多bug，例如我在“电影观看清单-状态控制（dvjs）”点击更新时间，选了“今天”，卡片没变，我又改为例如前一天，时间显示为前一天，再重新点击“今天”，才正确生效，显示为今天

**Comment by cumany** [comment]
使用本地图片的化示例库有例子 本地图片 用双链形式就可以 比如“[[让子弹飞海报.jpg]]”  然后用embed(image) 语法即可识别。

**Comment by cumany** [comment]
> 感觉好多bug，例如我在“电影观看清单-状态控制（dvjs）”点击更新时间，选了“今天”，卡片没变，我又改为例如前一天，时间显示为前一天，再重新点击“今天”，才正确生效，显示为今天

[template](https://github.com/cumany/Blue-topaz-examples/blob/main/.obsidian/plugins/templater-obsidian/main.js)
   用示例库的 template插件的文件覆盖下就可以了

**Comment by pikawindy** [comment]
ok，谢谢解答
