### ISSUE TITLE
react猫猫图像生成失效

### ISSUE THREAD

**Issue by wongtx** [cumany/Blue-topaz-examples#48]
如题，react插件配置完成，md文件也导入到正确位置，css文件也配置了，但是猫猫图片还是未生成。此外彩色时钟可以正常显示
感谢cuman制作了如此精美的实例库，受益良多。
![image](https://user-images.githubusercontent.com/46996862/187235552-dcbb548b-5575-4130-a93c-27f684046a2e.png)

**Comment by cumany** [comment]
react_cat 文件里的 99-Attachment/cat.gif 图片路径也需要更换成你自己的库路径

**Comment by wongtx** [comment]
已生效。感谢cuman
