### ISSUE TITLE
请问如何取消新建笔记后的弹窗？

### ISSUE THREAD

**Issue by wtfgfw1984** [cumany/Blue-topaz-examples#49]
![image](https://user-images.githubusercontent.com/35790873/188112123-62abfe79-1edf-4c33-9a6b-c5ae56948049.png)

**Comment by cumany** [comment]
![image](https://user-images.githubusercontent.com/42957010/188278631-75d6eaad-04d4-46ee-b899-7aecfae4ca9f.png)
templater 插件  这里触发 根目录创建文件调用的模板 可以删除选项也可以更换模板
