### ISSUE TITLE
在使用侧边栏工作区切换时，无法切换！

### ISSUE THREAD

**Issue by Xrebirth** [cumany/Blue-topaz-examples#5]
打开主题后，点击右侧边栏中的工作区先点击看板，在点击主页和记事没有反应，控制台报错：(Uncaught (in promise) TypeError: Cannot read property 'file' of null
    at clickHandler (eval at <anonymous> (app.js:1), <anonymous>:1555:51)
    at HTMLButtonElement.eval (eval at <anonymous> (app.js:1), <anonymous>:1549:15)
    at HTMLButtonElement.s (app.js:1))
Obsidian version：v0.3.23

**Comment by cumany** [comment]
经过测试 这是buttons插件的bug，建议用右下角的工作区切换功能，等buttons插件修复后再用按钮的方式调用命令。
![image](https://user-images.githubusercontent.com/42957010/153561140-32c490f8-c981-409a-bb4b-0ed38b36684a.png)

**Comment by cumany** [comment]
这个bug我已经提交了
[bug101](https://github.com/shabegom/buttons/issues/101)

**Comment by Xrebirth** [comment]
> 这个bug我已经提交了 [bug101](https://github.com/shabegom/buttons/issues/101)

好的
