### ISSUE TITLE
页面加载卡顿

### ISSUE THREAD

**Issue by vincentyang116** [cumany/Blue-topaz-examples#55]
Hi, 
    Thanks for your work! 示例库做的非常不错，感谢！
    请教一下，笔记浏览或编辑时上下滑动加载特别慢，是css效果加载的原因么？有什么能够解决的办法么？

**Comment by cumany** [comment]
参考 https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/issues/340

**Comment by vincentyang116** [comment]
不是这些原因，我把obsdian的GPU硬件加速关掉就好了，我是2019mbp。多谢哈。
