### ISSUE TITLE
这个补全的提示功能如何关闭？

### ISSUE THREAD

**Issue by jiechen257** [cumany/Blue-topaz-examples#57]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/73946940/197802349-2fa10867-ba76-4872-b5be-22615e6ffbd8.png">

我编辑文字一直弹出来下面的预选框，我不需要这个补全的提示，请问作者大大有办法关闭吗，或者告知下这是哪个插件的功能，我去把插件关闭使用

**Comment by cumany** [comment]
关闭这个插件即可
![image](https://user-images.githubusercontent.com/42957010/199480096-255814f1-e9a6-4ad4-a5c8-3e497f9b0c93.png)
