### ISSUE TITLE
搜刮豆瓣图书时，带特殊符号书名的文件会创建失败

### ISSUE THREAD

**Issue by Latias94** [cumany/Blue-topaz-examples#58]
https://github.com/cumany/Blue-topaz-examples/blob/ef60e5e8c86b8717db75fb1f018170322f12a502/88-Template/script/bookfromdouban.js#L148

例如这本书 [Rust for Rustaceans: Idiomatic Programming for Experienced Developers](https://book.douban.com/subject/35520588/) 书名带冒号，就会添加失败，建议多一个变量叫 filename 用来作为文件名，和 bookname 分开

**Comment by cumany** [comment]
修复豆瓣读书插件 如果图书名称包含特殊字符创建文件失败的问题。
注意需要修改quickadd 豆瓣读书宏命令。
【quickadd 获取豆瓣读书的宏命令，增加了filename字段用来给文件命名。】
