### ISSUE TITLE
汇报两个bug

### ISSUE THREAD

**Issue by iczrac** [cumany/Blue-topaz-examples#61]
1. Obsidian tray 在Macbook Pro M1上导致卡死，不能运作，删除后可运行
2. 日记的表情记录不能弹出选择

**Comment by cumany** [comment]
1, 估计是插件bug
2，侧边栏的工具栏 随笔 应该会出现表情选择
![image](https://user-images.githubusercontent.com/42957010/206888371-4d6d5a33-679e-40d5-98e2-2278866989df.png)

**Comment by iczrac** [comment]
> 1, 估计是插件bug
> 2，侧边栏的工具栏 随笔 应该会出现表情选择
> ![image](https://user-images.githubusercontent.com/42957010/206888371-4d6d5a33-679e-40d5-98e2-2278866989df.png)

嗯嗯  这个随笔可以 ，日记的不可以，请问要从哪里调整呢

**Comment by Ah-yuan** [comment]
有结果了么?

**Comment by cumany** [comment]
日记模板 里选择 带心情的模板即可 
![image](https://user-images.githubusercontent.com/42957010/206900991-f7feb69d-58c6-4d2f-b90b-6e1a2715a347.png)

**Comment by iczrac** [comment]
> 日记模板 里选择 带心情的模板即可
> ![image](https://user-images.githubusercontent.com/42957010/206900991-f7feb69d-58c6-4d2f-b90b-6e1a2715a347.png)

这个试过了  不行  不知道哪里出问题了

**Comment by iczrac** [comment]
````js quickadd
const suggester = await this.quickAddApi.suggester(["开心😀", "低落😐", "疲惫😪","爽😎","平静😶"], ["😀", "😐", "😪", "😎", "😶"]) 
return `banner_icon: ${suggester}`;
````
应该是这个新的语句有问题   显示 Metadata (Invalid YAML)

**Comment by cumany** [comment]
之前更新把文件修改了 这个语法通过quickadd调用可以识别 日历插件调用无法识别
如果想日历插件调用可以正确识别 建议用之前的文件
https://github.com/cumany/Blue-topaz-examples/blob/ffd45a97b1d11832e55b28fdc5dff3874386955b/88-Template/tp/tp-%E6%97%A5%E8%AE%B0%E6%A8%A1%E6%9D%BF-%E5%BF%83%E6%83%85.md

**Comment by iczrac** [comment]
> 之前更新把文件修改了 这个语法通过quickadd调用可以识别 日历插件调用无法识别
> 如果想日历插件调用可以正确识别 建议用之前的文件
> https://github.com/cumany/Blue-topaz-examples/blob/ffd45a97b1d11832e55b28fdc5dff3874386955b/88-Template/tp/tp-%E6%97%A5%E8%AE%B0%E6%A8%A1%E6%9D%BF-%E5%BF%83%E6%83%85.md

这个解决问题 🙏🏻️
