### ISSUE TITLE
textce link doesn't work

### ISSUE THREAD

**Issue by xfl888** [cumany/Blue-topaz-examples#62]
The link "https://textce.com/" in 50-Inbox\Website\文本处理-textce.md doesn't work. Could replace by "https://mytexttools.com/"

**Comment by cumany** [comment]
ok  thanks

**Comment by lsheng2** [comment]
reproduced with the Version: [20221208 完整版](https://github.com/cumany/Blue-topaz-examples/releases/tag/20221208)
