### ISSUE TITLE
In full version, button with url/link doesn't work

### ISSUE THREAD

**Issue by lsheng2** [cumany/Blue-topaz-examples#63]
Version: [20221208 完整版](https://github.com/cumany/Blue-topaz-examples/releases/tag/20221208)

The web page doesn't show up when click the button/icon of 飞书 on the home page. below are my findings:
1. any button defined with "type link" has the same problem
2. i replaced web browser plugin to https://github.com/Trikzon/obsidian-web-browser from the default "obsidian surfing". The issue disappeared.
3. no issue found with the lite version (maybe because it is opened by the external browser)

**Comment by cumany** [comment]
This is a problem caused by the surfing plugin, close the plugin, or wait for the plugin to update
