### ISSUE TITLE
home页天气栏月相无法加载

### ISSUE THREAD

**Issue by Xiuyee-d** [cumany/Blue-topaz-examples#68]
home页加载后如下图：
![image](https://user-images.githubusercontent.com/61900174/212142772-3dc34f7e-7612-4489-8239-8e75152940cb.png)

月相加载失败，切换编辑模式查看源代码：
![image](https://user-images.githubusercontent.com/61900174/212145806-bda1aedf-fd9d-4f36-83c0-26607cbdbd65.png)

此处调用的是NASA提供的365*24=8760个月相帧文件，索引值为4位整型，索引值少于4位时头部应补0，对moonIndex变量进行处理，修改为`let moonIndex = moment().diff(moment().startOf('year'),"hours").toString().padStart(4, '0');`

此时再查看天气栏，可以发现月相已成功加载：
![image](https://user-images.githubusercontent.com/61900174/212146661-01c95017-3e93-444c-be9a-0fa45faadab4.png)

**Comment by cumany** [comment]
很棒~！ 已采纳
