### ISSUE TITLE
关于20221208 lite 精简版 的一些问题

### ISSUE THREAD

**Issue by Pcodcsja** [cumany/Blue-topaz-examples#69]
![image](https://user-images.githubusercontent.com/66547114/212865441-1df83d50-410f-4ae2-8342-d1f62c3bcecd.png)
上图中红色框中文字乱码问题以及黄色框中能否将图标改成两行或者三行 现在这样太占用空间了 如果将它向右缩的话图标又无法完全显示
以及在首页点击 Inbox 会出现错误（如下图所示）
![image](https://user-images.githubusercontent.com/66547114/212866582-5d1e9aa7-83ad-45e7-b3e2-32879ff6d09a.png)

Obsidian版本为V1.1.9

**Comment by cumany** [comment]
第一个问题乱码无视 或者删除即可 因为这个是通过豆瓣自动获取的内容，你可以重新用豆瓣脚本 获取新的内容即可

第二个问题，是因为你没有更新主题，更新主题后重启ob 即可解决
