### ISSUE TITLE
作者您好，最近更新的主题，有个bug帮看下！！

### ISSUE THREAD

**Issue by lyeeo** [cumany/Blue-topaz-examples#91]
打开核心插件中的文档属性视图，可以显示所有属性的汇总面板
ctrl+p 命令，输入文档属性，可以打开  只显示当前文件的属性 面板视图

之前这个 当前文件的属性面板视图 是可以显示和添加当前 文档属性的

主题更新后，  当前文件的属性面板视图  就什么都没了  不能显示当前文档已有的属性，也不能添加其他属性

变成空白的了

只有换其他主题后，当前文件的属性面板视图  才能恢复正常

辛苦，看看，是什么问题，修改下 谢谢

**Comment by lyeeo** [comment]
![1](https://github.com/PKM-er/Blue-topaz-example/assets/132392142/cbbb9f46-ec71-4464-88ca-44c24f912991)

**Comment by cumany** [comment]
更新下个版本主题即可修复

**Comment by lyeeo** [comment]
谢谢~
